# schema: https://github.com/openshift/installer/blob/master/pkg/types/installconfig.go
apiVersion: v1
metadata:
  name: ${CLUSTER_NAME}
baseDomain: ${BASE_DOMAIN}
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      defaultMachinePlatform:
        type: m6i.4xlarge
  replicas: 3
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    aws:
      defaultMachinePlatform:
        type: m6i.4xlarge
  replicas: 5
networking:
  networkType: OVNKubernetes
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-east-1
    privateLink: true  # Mengaktifkan PrivateLink untuk komunikasi internal AWS
    subnets:  # Memastikan subnet yang sudah didefinisikan digunakan
      - subnet-xxxxxx  # Ganti dengan subnet ID untuk master nodes
      - subnet-yyyyyy  # Ganti dengan subnet ID untuk worker nodes
      - subnet-zzzzzz  # Tambahkan jika perlu lebih banyak subnet
    serviceEndpoints:  # Menentukan endpoint AWS agar tetap dalam PrivateLink
      - name: ec2
        url: https://ec2.us-east-1.amazonaws.com
      - name: s3
        url: https://s3.us-east-1.amazonaws.com
      - name: elasticloadbalancing
        url: https://elasticloadbalancing.us-east-1.amazonaws.com
      - name: sts
        url: https://sts.us-east-1.amazonaws.com
publish: Internal  # Mengubah dari "External" ke "Internal" agar tidak terbuka ke internet
pullSecret: '${OPENSHIFT_PULL_SECRET}'
sshKey: '${SSH_PUBLIC_KEY}'
