apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  name: "instance"
  namespace: "openshift-logging"
spec:
  managementState: "Managed"
  logStore:
    type: "elasticsearch"
    retentionPolicy:
      application:
        maxAge: 14d
      infra:
        maxAge: 14d
      audit:
        maxAge: 14d
    elasticsearch:
      nodeCount: 3
      tolerations:
        - key: "node-role.kubernetes.io/infra"
          operator: "Exists"
          effect: "NoSchedule"
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      storage:
        storageClassName: "sc-logging"
        size: 500G
      resources:
        limits:
          memory: "16Gi"
        requests:
          memory: "8Gi"
  proxy:
    resources:
      limits:
        memory: 256Mi
      requests:
        memory: 256Mi
  redundancyPolicy: "SingleRedundancy"
  visualization:
    type: "kibana"
    kibana:
      tolerations:
        - key: "infra"
          operator: "Exists"
          effect: "NoSchedule"
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      replicas: 1
  collection:
    logs:
      type: "fluentd"
      fluentd:
        tolerations:
          - key: "node-role.kubernetes.io/infra"
            operator: "Exists"
            effect: "NoSchedule"
